import { Page, Text, View, Image } from '@react-pdf/renderer'
import { baseStyles, colors, getScoreColor } from './styles'

// Re-export styles for convenience
export { baseStyles, colors, getScoreColor }

interface CoverPageProps {
  logoUri: string
  title: string
  subtitle?: string
  date: string
  score?: number | null
  variant?: 'dark' | 'light'
}

export function CoverPage({
  logoUri,
  title,
  subtitle,
  date,
  score,
  variant = 'dark',
}: CoverPageProps) {
  const isLight = variant === 'light'
  const pageStyle = isLight ? baseStyles.coverPageLight : baseStyles.coverPage
  const titleColor = isLight ? colors.primary : colors.white
  const subtitleColor = isLight ? colors.textLight : colors.muted

  return (
    <Page size="A4" style={pageStyle}>
      <View style={baseStyles.coverContent}>
        {/* eslint-disable-next-line jsx-a11y/alt-text -- @react-pdf/renderer Image doesn't support alt */}
        {logoUri && <Image src={logoUri} style={baseStyles.logo} />}
        <Text style={[baseStyles.coverTitle, { color: titleColor }]}>{title}</Text>
        {subtitle && (
          <Text style={[baseStyles.coverSubtitle, { color: subtitleColor }]}>{subtitle}</Text>
        )}
        <Text style={[baseStyles.coverSubtitle, { color: subtitleColor }]}>{date}</Text>
        {score !== undefined && score !== null && (
          <View style={{ marginTop: 40 }}>
            <ScoreBadge score={score} size="large" label="Overall Score" />
          </View>
        )}
      </View>
      <Text style={[baseStyles.coverFooter, isLight ? { color: colors.textLight } : {}]}>
        Generated by Selo Studios
      </Text>
    </Page>
  )
}

interface ScoreBadgeProps {
  score: number | null
  size?: 'small' | 'large'
  label?: string
}

export function ScoreBadge({ score, size = 'small', label }: ScoreBadgeProps) {
  const fontSize = size === 'large' ? 48 : 28
  const padding = size === 'large' ? 24 : 16
  const labelSize = size === 'large' ? 12 : 9

  return (
    <View
      style={{
        backgroundColor: size === 'large' ? colors.white : colors.secondary,
        padding,
        borderRadius: 8,
        alignItems: 'center',
        minWidth: size === 'large' ? 120 : 80,
      }}
    >
      <Text
        style={{
          fontSize,
          fontWeight: 'bold',
          color: getScoreColor(score),
        }}
      >
        {score ?? '-'}
      </Text>
      {label && (
        <Text
          style={{
            fontSize: labelSize,
            color: colors.textLight,
            textTransform: 'uppercase',
            marginTop: 4,
          }}
        >
          {label}
        </Text>
      )}
    </View>
  )
}

interface SectionHeaderProps {
  title: string
}

export function SectionHeader({ title }: SectionHeaderProps) {
  return <Text style={baseStyles.sectionTitle}>{title}</Text>
}

interface IssueCardProps {
  name: string
  priority: 'critical' | 'recommended' | 'optional'
  description?: string
  fixGuidance?: string
}

export function IssueCard({ name, priority, description, fixGuidance }: IssueCardProps) {
  const cardStyle =
    priority === 'critical' ? baseStyles.issueCardCritical : baseStyles.issueCardWarning

  const priorityColor =
    priority === 'critical'
      ? colors.error
      : priority === 'recommended'
        ? colors.warning
        : colors.textLight

  return (
    <View style={[baseStyles.issueCard, cardStyle]}>
      <Text style={baseStyles.issueName}>{name}</Text>
      {description && <Text style={baseStyles.issueDescription}>{description}</Text>}
      {fixGuidance && (
        <Text style={baseStyles.issueFixGuidance}>
          <Text style={{ fontWeight: 'bold' }}>Fix: </Text>
          {fixGuidance}
        </Text>
      )}
      <Text style={[baseStyles.issuePriority, { color: priorityColor }]}>{priority}</Text>
    </View>
  )
}

interface StatBarProps {
  stats: Array<{
    value: number | string
    label: string
    color?: string
  }>
}

export function StatBar({ stats }: StatBarProps) {
  return (
    <View style={baseStyles.statsRow}>
      {stats.map((stat, index) => (
        <View key={index} style={baseStyles.statItem}>
          <Text style={[baseStyles.statValue, stat.color ? { color: stat.color } : {}]}>
            {stat.value}
          </Text>
          <Text style={baseStyles.statLabel}>{stat.label}</Text>
        </View>
      ))}
    </View>
  )
}

interface PageFooterProps {
  text: string
  pageNumber?: number
}

export function PageFooter({ text, pageNumber }: PageFooterProps) {
  return (
    <Text style={baseStyles.pageFooter}>
      {text}
      {pageNumber !== undefined && ` - Page ${pageNumber}`}
    </Text>
  )
}

interface ActionItemProps {
  number: number
  text: string
}

export function ActionItem({ number, text }: ActionItemProps) {
  return (
    <View style={baseStyles.actionItem}>
      <Text style={baseStyles.actionNumber}>{number}.</Text>
      <Text style={baseStyles.actionText}>{text}</Text>
    </View>
  )
}

interface ContactBoxProps {
  title?: string
  email?: string
  website?: string
}

export function ContactBox({
  title = 'Get in Touch',
  email = 'hello@selostudios.com',
  website = 'selostudios.com',
}: ContactBoxProps) {
  return (
    <View style={baseStyles.contactBox}>
      <Text style={baseStyles.contactTitle}>{title}</Text>
      <Text style={baseStyles.contactItem}>Email: {email}</Text>
      <Text style={baseStyles.contactItem}>Website: {website}</Text>
    </View>
  )
}

interface PassedChecksSummaryProps {
  count: number
}

export function PassedChecksSummary({ count }: PassedChecksSummaryProps) {
  return (
    <View style={baseStyles.passedSummary}>
      <Text style={{ fontSize: 12, color: colors.success }}>✓</Text>
      <Text style={baseStyles.passedText}>
        {count} check{count !== 1 ? 's' : ''} passed
      </Text>
    </View>
  )
}
